name: Project Greystorm Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Setup nodejs
          uses: actions/setup-node@v4
          with:
            version: 20

        - name: Install Dependencies
          run: npm Install

        - name: Unit Testing
          run: npm test --if-present

        - name: Run Code Coverage
          run: npm run coverage --if-present
